name: corazon_clean
description: "A new Flutter project for Corazon App."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  uuid: ^4.5.3
  firebase_core: ^4.11.0
  cloud_firestore: ^6.6.0
  firebase_auth: ^6.5.3
  firebase_storage: ^13.4.3
  
  # Tambahan library untuk import Excel (Web Admin) stuy
  file_picker: ^11.0.2
  excel: ^4.0.6
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Pendaftaran folder assets gambar kamu stuy
  assets:
    - assets/images/